# Copia este fichero como sonar-project.properties (está en .gitignore porque contiene el token)
sonar.projectKey=dwcle-template
sonar.projectName=DWCLE Template
sonar.host.url=http://localhost:3300
# Token generado en SonarQube > My Account > Security
sonar.token=sqp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

sonar.projectBaseDir=../..
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
